# Generated by Django 5.2.3 on 2025-06-30 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_codingquestion_students'),
        ('user', '0005_useranswer_userlesson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='students',
            field=models.ManyToManyField(related_name='lessons', through='user.UserLesson', to=settings.AUTH_USER_MODEL),
        ),
    ]
