# Generated by Django 5.2.3 on 2025-07-06 12:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lesson_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_materials',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='materials'),
        ),
    ]
