# Generated by Django 5.2.3 on 2025-07-08 06:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson_lesson_materials'),
        ('user', '0006_usercomponent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='student',
            field=models.ManyToManyField(related_name='components', through='user.UserComponent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='coding_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
