# Generated by Django 5.2.3 on 2025-07-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_codingquestion_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingquestion',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('c', 'C'), ('c++', 'C++'), ('javascript', 'Javascript')], default='python', max_length=15),
        ),
        migrations.AddField(
            model_name='codingquestion',
            name='pre_written_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
