# Generated by Django 5.2.3 on 2025-07-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_codingquestion_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingtest',
            name='input',
            field=models.TextField(blank=True, null=True),
        ),
    ]
