# Generated by Django 5.2.3 on 2025-08-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_usercomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
    ]
